favicon: null
name: steelmountain
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.7370152
  brandStrength: 0.39803846180439
  lightness: 0.2295622
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  rhythmicContrast: 0
typography_spectrum: 0.3922402462922037
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9408602
analytics:
  twitter: null
  google: null
  facebook: null
