name: steelmountain
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.3351254
  brandStrength: 0
  lightness: 0.2921147
  brandColors:
    - '#3A3B36'
    - '#FFC6AE'
    - '#83A9CE'
    - '#827258'
    - '#FFFFFF'
  rhythmicContrast: 0.5913978
typography_spectrum: 0.3922402462922037
layout_spectrum: 0.9408602
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
