favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0
  brandStrength: 0.39803846180439
  lightness: 1
  brandColors:
    - '#4E3A17'
    - '#0C0B06'
    - '#DDE4C2'
    - '#818340'
    - '#C9AE74'
  rhythmicContrast: 0
typography_spectrum: 0.3922402462922037
layout_spectrum: 0.9408602
analytics:
  twitter: null
  google: null
  facebook: null
name: steelmountain
